name: udemy-project5
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      #this make sure our code is download in the runner machine
      - name: Get code
        uses: actions/checkout@v3
      #install dependencies
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm init @eslint/config
      - name: test code
        run: npm run test
      - name: build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.json
      - name: deploy code
        run: echo "deploying...."
    
 




